[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "ISC",
    "ICN",
    "INP",
    "PIE",
    "PYI",
    "PT",
    "RSE",
    "SLF",
    "NPY",
    "PERF",
    "RUF",
]
ignore = [
    "D1",
    "PT011",
    "PT018",
    "PERF203",
    "RUF005",
]
pydocstyle.convention = "google"

[tool.ruff.format]
preview = true
